[versions]

# Minecraft
minecraft = "26.2"
loom = "1.17-SNAPSHOT"
loader = "0.19.3"

# Dependencies
fabric = "0.155.0+26.2"
fabrickotlin = "1.13.13+kotlin.2.4.10"
hypixelapi = "1.0.2+build.1+mc26.1"
olympus = "1.9.0"
rlib = "5.0.2"

# Dev Dependencies
devauth = "1.2.2"
modmenu = "20.0.1"

[libraries]

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
fabrickotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabrickotlin" }
hypixelapi = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelapi" }
modapi = { module = "net.hypixel:mod-api", version = "1.0.2" }
olympus = { module = "earth.terrarium.olympus:olympus-fabric-26.2", version.ref = "olympus" }
rlib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-26.2", version.ref = "rlib" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]

loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
