[versions]

# Minecraft
minecraft = "1.21.8"
loom = "1.11-SNAPSHOT"
loader = "0.16.14"

# Dependencies
fabric = "0.129.0+1.21.8"
fabrickotlin = "1.13.3+kotlin.2.1.21"
hypixelapi = "1.0.1+build.1+mc1.21"
olympus = "1.5.2"
rlib = "3.6.0"

# Dev Dependencies
devauth = "1.2.1"
modmenu = "15.0.0-beta.3"

[libraries]

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
fabrickotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabrickotlin" }
hypixelapi = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelapi" }
modapi = { module = "net.hypixel:mod-api", version = "1.0.1" }
olympus = { module = "earth.terrarium.olympus:olympus-fabric-1.21.7", version.ref = "olympus" }
rlib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.6", version.ref = "rlib" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]

loom = { id = "fabric-loom", version.ref = "loom" }
